### ISSUE TITLE
Recommended Webmock integration is incorrect

### ISSUE THREAD

**Issue by paneq** [algolia/algoliasearch-client-ruby#100]
Hey,

I think the recommended webmock setup in https://github.com/algolia/algoliasearch-client-ruby#mocking does not work in case of multiple test files because `require` will only load the code once. I think the stubs needs to be loaded in every test. Here is what I am doing instead:

```
RSpec.describe Event do

  specify do
    load $LOADED_FEATURES.find{|x| x.include?("algolia/version.rb") }.gsub("version.rb", "webmock.rb")

    # code which triggers algolia integration goes here....

    expect(WebMock).to have_requested(:put, "https://application_id.algolia.net/1/indexes/events/#{event.id}").
      with(body: hash_including({
        "objectID": event.id.to_s,
        "name": "dummy event",
        "category": "music",
      }))
  end

end
```

The key difference is that I do `load` instead of `require`. Unfortunately doing `load 'algolia/webmock'` did not just work so I had to use `$LOADED_FEATURES.find{|x| x.include?("algolia/version.rb") }.gsub("version.rb", "webmock.rb")` to find the file and load it.

I need to do it in every affected test.

**Comment by redox** [comment]
> I think the stubs needs to be loaded in every test

Hmmm, maybe that's because you disable the mocking in a `helper` file or something required in every single test file?

In such case, the `require` should be done there as well.

> The key difference is that I do load instead of require. Unfortunately doing load 'algolia/webmock' did not just work so I had to use $LOADED_FEATURES.find{|x| x.include?("algolia/version.rb") }.gsub("version.rb", "webmock.rb") to find the file and load it.

Yes, not very convenient :/

**Comment by paneq** [comment]
> In such case, the require should be done there as well.

How would that help if the `require` is only executed once and that's the point of using `require` over `load` ?

As to our setup, `rails_helper` has:

```
  config.before(:each) do |example|
    WebMock.disable_net_connect!(allow_localhost: true, allow: "localhost:9200")
  end

  config.after(:each) do |example|
    WebMock.allow_net_connect!
  end
```

**Comment by redox** [comment]
So should we wrap all the stubs in a method you could call in your `config.before` to setup everything?

Something like: `Algolia::WebMock.enable!` ?

**Comment by paneq** [comment]
@redox sounds like a good approach.

**Comment by mintuhouse** [comment]
I am facing a similar issue. What is a recommended way to mock all algolia requests across the test suite?
