### ISSUE TITLE
filters have strange behavior

### ISSUE THREAD

**Issue by Maryskr** [algolia/algoliasearch-client-ruby#120]
Hi! I use Algolia search for my application.
There are several filters on my search page. When I try to use parameter `filter: 'attribute:name'` for
 my request, I get a very strange response. It returns empty array in most cases, but sometimes search results are correct.
Please, look at screenshot:
![image](https://cloud.githubusercontent.com/assets/7038753/21191513/67418af0-c236-11e6-85ed-2556da7b3cce.png)

**Comment by redox** [comment]
Hey @Maryskr;

that should have been created in https://github.com/algolia/algoliasearch-rails but not a big deal :) 

It's indeed very surprising: could you give a try to the [`algolia_raw_search`](https://github.com/algolia/algoliasearch-rails#backend-search) to test if you have the same bug bypassing the ActiveRecords loading?

Also, would you be able to trace the queries that are actually performed from your Algolia dashboard; and check if you're able to reproduce the issue using the web interface?

**Comment by Maryskr** [comment]
Also I get a empty response using raw search:

`irb(main):129:0> User.algolia_raw_search('', filters: 'first_name:Mary')
=> {"hits"=>[], "nbHits"=>0, "page"=>0, "nbPages"=>0, "hitsPerPage"=>20, "processingTimeMS"=>1, "query"=>"", "params"=>"filters=first_name%3AMary&query="}`

But I am sure that my index has at least two hits.
Sorry, but I don't know how can I reproduce this request via web interface, 'cause there are only tag, facet and numeric filters at query parameters menu. But I need to filter the results only by attribute (first_name for example)

**Comment by redox** [comment]
Hmmm, but `first_name` is part of your facets; right? It should be a facet and therefore you should use the face filtering capabilities.

**Comment by Maryskr** [comment]
Oh, I found an issue at my code. Don't know why, but I don't add `first_name` attribute to `attributesForFaceting` for User model, that's why a get an empty response. It's my mistake. Now it works correct!
Thanks a lot for help!
