### ISSUE TITLE
Issue with hosts session

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-client-ruby#13]
My shopify app needs to connect to multiple algolia instances. Hence, I'm calling `Algolia.init` each time I'm dealing with something for a specific client.
When I'm looking at the `Algolia.client`, the info is OK. However, when trying to call Algolia, I got a "403 APP-ID or API key invalid".
I investigated a bit, and found out that the issue was due to the fact that we have a specific client per thread in `Thread.current[:algolia_hosts]`, and that we always get back the same one, even when the client is changed. I belive it should be set during the `initialize` instead of in [`thread_local_hosts` if not defined](https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/client.rb#L101-L118).
My solution to this is to do a `Thread.current[:algolia_hosts] = nil`, but I believe this should be handled differently.

What do you think?

**Comment by redox** [comment]
Yeah, multiple instantiations of the ruby API client in the same process is not really supported. That being said, if you ensure you don't run in a multi-threaded environment; you can do:

```ruby
Algolia.init .....
# FIXME
Algolia.destroy # destroy the underlying thread-local http clients
Algolia.init ....
# FIXME
```
