### ISSUE TITLE
search should use a POST request

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-ruby#14]

**Comment by redox** [comment]
@Dagnan Let me know what you think!

**Comment by redox** [comment]
Part of `1.6.1`.

**Comment by Dagnan** [comment]
I still have this:
```
400: Cannot POST to https://---.algolia.net/1/indexes/*/queries?strategy=none: {"message":"query string too long","status":400} (400)
```

BTW our endpoint to the plugin is `Algolia.multiple_queries(queries)`

**Comment by redox** [comment]
That's not the same thing (400 - bad request here); that's because your query string (the `query` query parameter) is probably longer than 512 chars, do you confirm?

**Comment by Dagnan** [comment]
Ah yeah it's possible. I'll investigate tomorrow.

**Comment by henrikbackman** [comment]
@Dagnan Was that the issue? I have the same problem.

**Comment by redox** [comment]
@henrikbackman you mean you have a `400 bad request` (query string too long) or a `414 Request URI too long` error ?

**Comment by henrikbackman** [comment]
@redox Query string too long.

**Comment by redox** [comment]
@henrikbackman you should just upgrade to `algoliasearch=1.6.1` then; it should fix your issue

**Comment by Dagnan** [comment]
@redox Maybe the 512 chars limitation would be useful in the doc. What do you think?

**Comment by Dagnan** [comment]
Actually 512 still raises errors. 400 is ok.
