### ISSUE TITLE
Error on the delete_by_query method when Distinct > 1

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-client-ruby#16]
In the case the distinct is enabled on an index (with distinct > 1), a call to the method delete_by_query returns the following error:

```
{
  "message": "invalid distinct value, hitsPerPage * distinct should be <= 1000",
  "status": 400
}
```

We should probably override `distinct=false` at query time when the method performs the search call.

**Comment by vincentwoo** [comment]
@redox I do not believe this issue was fixed in the linked commit. I am running into this now - enabling distinct on your index breaks delete by query (at least in the Ruby client).
