### ISSUE TITLE
operation: should be a hashrocket?

### ISSUE THREAD

**Issue by reinaris** [algolia/algoliasearch-client-ruby#17]
https://github.com/algolia/algoliasearch-client-ruby/blame/master/README.md#L245

Shouldn't that be `operation =>` instead of `operation:`?

**Comment by redox** [comment]
Oh yes correct

**Comment by reinaris** [comment]
https://github.com/algolia/algoliasearch-client-ruby/compare/master...reinaris:patch-1

**Comment by reinaris** [comment]
too fast ;)
