### ISSUE TITLE
Support batch operations on writing to multiple indexes

### ISSUE THREAD

**Issue by l4u** [algolia/algoliasearch-client-ruby#18]
Probably a prerequisite to https://github.com/algolia/algoliasearch-rails/issues/22

**Comment by danlo** [comment]
+1

**Comment by redox** [comment]
Hey @danlo,

do you have a use-case with a lot of indices? Because this adds a bunch of complexity for probably not a lot of improvements (mostly because of the keep-alive).

**Comment by danlo** [comment]
Yes.  Basically on our site, we have many "communities" each with their own collection of data (lawyers, guides, packages).  To insure that data from one community never can get into another we break things up into their own indexes  [community] x [lawyers, guides, packages]

During the update process, I just batch everything up and make "n" requests (1000 record updates).

**Comment by danlo** [comment]
The existing gem you have 1.10.0 supports this feature, however, the master code is different from the 1.10.0 code in that "master" will put in ruby
```
requests: [requests]
```

Where in 1.10.0 you have to put in {requests: [requests]}

**Comment by julienbourdeau** [comment]
I'll close this issue since this is supported by the client. Please find related documentation here: https://www.algolia.com/doc/api-reference/api-methods/batch/
