### ISSUE TITLE
Missing doc for `set_extra_header`

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-client-ruby#196]
The method is mentioned in the Geosearch guide to pass `X-Forwarded-For` to the engine when doing a backend implementation, but the method is not documented at the API client level so it's hard to know it actually exists :)

**Comment by redox** [comment]
It's not implemented in the Ruby client actually :/

**Comment by olance** [comment]
@redox Are you sure?
https://github.com/algolia/algoliasearch-client-ruby/blob/caff6bd17e751a9b213aefc30dddab3b170789e6/lib/algolia/client.rb#L61-L63

**Comment by redox** [comment]
> @redox Are you sure?
> https://github.com/algolia/algoliasearch-client-ruby/blob/caff6bd17e751a9b213aefc30dddab3b170789e6/lib/algolia/client.rb#L61-L63

Ah yes OK, I misunderstood the issue 👍

**Comment by olance** [comment]
Ah, sorry!
I guess "the method" was maybe not super explicit 😅

**Comment by julienbourdeau** [comment]
I guess this was fixed some times ago: https://www.algolia.com/doc/api-reference/api-methods/set-extra-header/?language=ruby

Thanks!
