### ISSUE TITLE
Get tasks status without waiting for a task to finish

### ISSUE THREAD

**Issue by srodman7689** [algolia/algoliasearch-client-ruby#199]
Hey guys, I have need of a method that will return the status of a task given the task id. I have created a pull request that makes this change here https://github.com/algolia/algoliasearch-client-ruby/pull/198 but in the case that this isn't how you guys would want to go about it I decided to post an issue here. That way if you guys want to go about it a different way there will still be a record of it.

**Comment by redox** [comment]
`1.13.0` has been released!
