### ISSUE TITLE
Bundle won't update latest version of gem (1.12.7)

### ISSUE THREAD

**Issue by antonio97b** [algolia/algoliasearch-client-ruby#200]
I've tried running a `bundle install` and even a manual `gem install algoliasearch-rails` and bundler doesn't seem to want to touch this new gem. I have some funky stuff going on with Algolia and I want to see if this is the issue. If anyone can explain why bundler would not update this gem, let me know.

Here is the relevant part of my Gemfile:

```
# Search
gem 'algoliasearch', '~> 1.6', '>= 1.6.1'
gem "algoliasearch-rails"
```

**Comment by redox** [comment]
What if you run `bundle update algoliasearch`?

**Comment by sobrinho** [comment]
Problem with algoliasearch-rails instead of algoliasarch, see https://github.com/algolia/algoliasearch-rails/pull/267.
