### ISSUE TITLE
Multithreading issue with multiple hosts

### ISSUE THREAD

**Issue by meltingice** [algolia/algoliasearch-client-ruby#202]
In our application, we make requests to both the search API and the analytics API using this client. Unfortunately, there seems to be a pretty major multithreading issue where the wrong host gets picked for requests. For example, we've had indexing PUT requests go to the analytics API, and analytics GET requests attempt to use the indexing API.

From my light exploration, the problem seems to lie with the fact that hosts are stored in a global per-thread state, even if you manually initialize the client with `Algolia::Client.new`.

We use this library in conjunction with `algoliasearch-rails`, so we have models that are being indexed with that gem, as well as some controller code for fetching analytics. We initialize the analytics client with:

``` ruby
@algolia ||= Algolia::Client.new(
  application_id: ENV['ALGOLIA_APP_ID'],
  api_key: ENV['ALGOLIA_API_KEY'],
  hosts: ["analytics.algolia.com"]
)
```

Let me know if there's any more info you need, or if you would like me to take a crack at this issue.

**Comment by meltingice** [comment]
So it looks like one way to avoid this issue is to call `.destroy` on the client both before and after the analytics call, which clears out the global per-thread hosts.

**Comment by redox** [comment]
Hi @meltingice,

> Let me know if there's any more info you need, or if you would like me to take a crack at this issue.

thank you for this detailed explanation. The Ruby API client is actually not designed to call our analytics API -> for the Analytics API I recommend to use a regular `RestClient`. Otherwise, as you've mentioned this will mess up the underlying *thread-local* data-structure using the `APPLICATION_ID` as keys.

Does that make sense?

**Comment by chloelbn** [comment]
I'm closing this issue as the singleton client will be removed in our next version and a solution has been provided for the current one. Don't hesitate and reopen it if you think something is missing.
