### ISSUE TITLE
Should there be a `delete_by_query!` method?

### ISSUE THREAD

**Issue by jmirmina** [algolia/algoliasearch-client-ruby#204]
The `delete_object` and `delete_objects` methods both have a `!` version that will actually wait until the delete has taken place before returning. It appears that the `delete_by_query` method goes against this and waits by default. Is there any reason that this operation would need to wait?

**Comment by obahareth** [comment]
I was actually having a huge slow-down in my Rails app due to `delete_by_query` waiting. I expected it to work like the versions without `!` and be asynchronous. The [C# version for delete by query](https://www.algolia.com/doc/api-client/csharp/indexing/#delete-by-query) is async.
