### ISSUE TITLE
Performance issues with PUT/POST

### ISSUE THREAD

**Issue by Gasparila** [algolia/algoliasearch-client-ruby#205]
The Algolia::Client post, put, and delete requests all make a network call to Algolia. Recently, we have started noticing performance issues where put calls are taking ~300ms apiece. It seems like an easy solution (that we are currently monkey patching successfully) is to make post requests async (which HTTPClient supports) and optimistically assume the update will succeed. Is this a feature you could add so we can stop monkey patching our gem?

**Comment by victorhazbun** [comment]
Does this has something to be with the Ruby gem or the Algolia servers responses?

**Comment by chloelbn** [comment]
As this discussion has no follow up I'm closing the issue. Don't hesitate and open it back if the problem still exist.
