### ISSUE TITLE
NoMethodError: undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by cupofjoakim** [algolia/algoliasearch-client-ruby#207]
It's getting thrown around in my tests a lot and I can't figure out why. This is the line that fails:

`@users = User.search(search_string)`

It feels like I'm missing something obvious, but I don't know what

**Comment by redox** [comment]
Any chance you could provide us the full backtrace? I assume something happens while computing pagination's metadata; are you using Kaminari or will_paginate in your model?

**Comment by cupofjoakim** [comment]
Sorry @redox , this was an issue from the rails gem. My mistake. I'll recreate this issue over there instead.
