### ISSUE TITLE
Missing stubbed requests

### ISSUE THREAD

**Issue by alexandremeunier** [algolia/algoliasearch-client-ruby#21]
When requiring `algolia/webmock`, it will only stub `algolia.(net|io)` requests. _([Source](https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/webmock.rb))_

However, the client [sometimes](https://github.com/algolia/algoliasearch-client-ruby/blob/cd53cd3fb4e34364dae19c2930d05c00636876dd/lib/algolia/client.rb#L29-L30) makes requests to `algolianet.com`. Are those intentionally not stubbed ? If it is a mistake, happy to do a PR.

cc @Nagriar

**Comment by Jerskouille** [comment]
You could probable replace `.io` with `algolianet.com` since we're not using it anymore I believe.
