### ISSUE TITLE
Cannot apply a delete request on a replica index

### ISSUE THREAD

**Issue by mustela** [algolia/algoliasearch-client-ruby#210]
Hey there, I'm trying to remove dynamically some replicas, but it seems I can't do that, without manually disassociate it from the main index. I couldn't find anything in here, rails client, and algolia api docs that tell me how to do it... is not supported? 

Thanks

**Comment by timramseyjr** [comment]
Did you ever figure this out?

**Comment by timramseyjr** [comment]
I am using the php client, but I found that if I set the `$index->setSettings(['replicas' => []]);` (removed index from the replicas), and `sleep(1)` that I could get it to work, but I assumed there would be a way to force delete a replica.

**Comment by timramseyjr** [comment]
You have to wait for the replica to be removed in the settings before deleting.  I looks something like:

```
$res = $index->setSettings(['replicas' => []]);
$index->waitTask($res['taskID']);
$client->deleteIndex('someindex');
```

**Comment by raphi** [comment]
Thanks @timramseyjr, that's indeed the way to go.
