### ISSUE TITLE
Code from documentation on browse method returning 400

### ISSUE THREAD

**Issue by dustincoates** [algolia/algoliasearch-client-ruby#22]
``` ruby
index.browse({
  query: 'test'
})
```

A slightly modified version of the code from the README. Getting back a `{"message":"Invalid value for page parameter","status":400}`.

Here's the URL it's trying to hit:
`https://FOO.algolia.net/1/indexes/BAR/browse?page=%7B%3Aquery%3D%3E%22test%22%2C+%3Apage%3D%3E1%7D&hitsPerPage=1000`

**Comment by redox** [comment]
Oh yes, you need to pass a block; otherwise it try to pass your argument as the `page` query parameter. Will fix that.

**Comment by dustincoates** [comment]
@redox Uuf, makes sense, thanks. :+1:

Do you think it would make sense to raise an argument error if no block?

**Comment by redox** [comment]
> Do you think it would make sense to raise an argument error if no block?

Yes, if the parameter is a `Hash` and no block; definitely!

**Comment by Jerskouille** [comment]
I believe this should be closed.
