### ISSUE TITLE
Document method to generate secured API key

### ISSUE THREAD

**Issue by oyeanuj** [algolia/algoliasearch-client-ruby#228]
Hi folks, I found the method to generate secured API key via support but figured it might be worth creating a ticket incase others come looking for the same:

Found the method here: https://github.com/algolia/algoliasearch-client-ruby/blob/2480006144020dae044b4e5dd3db8dc5f8cb9f2b/lib/algolia/client.rb#L500

It would be super helpful to see this in the README, with an example or two.

Thank you!

**Comment by redox** [comment]
Hi @oyeanuj,

right the full-reference of our documentation is currently hosted on our algolia.com website. The documentation of secured api keys is there: https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/

I'll forward your feedback to our doc team, I get it can be confusing.

**Comment by oyeanuj** [comment]
@redox Thanks for the quick response, and for that link.. missed that somehow!

**Comment by raphi** [comment]
@oyeanuj thanks for your feedback. 
We now list all available methods here:
https://github.com/algolia/algoliasearch-client-ruby#list-of-available-methods

**Comment by redox** [comment]
> @redox @raphi thank you! One quick followup: Is this not available in the Rails Gem? Or can I use any method provided here from the Rails Gem as well? or do you recommend using both?

You can access the underlying Ruby API client from the rails gem at any time by using the `MyModel.index` class method. So I would recommend using this to generate the secured API keys.
