### ISSUE TITLE
Add request logging to client

### ISSUE THREAD

**Issue by ajsharp** [algolia/algoliasearch-client-ruby#23]

**Comment by ajsharp** [comment]
bump

**Comment by redox** [comment]
Hi @ajsharp,

could you provide more details about why you need request logging? Is it for debug? Is it to track the time spent in the network or so?

What I'm used to do to debug the requests that are done is to set the underlying `debug_dev` (https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L456-L464) attribute to `$stderr` or something.

**Comment by mintuhouse** [comment]
Can you provide an example of how do I set debug_dev in context of using the gem in a rails app?

**Comment by Jerskouille** [comment]
You should be able to use the [`httplog`](https://github.com/trusche/httplog) for that.
If you're having issues with `gzip`, you can now instantiate the client with `gzip: false` (#240) .
