### ISSUE TITLE
Error saving synonym with numeric objectID

### ISSUE THREAD

**Issue by jmirmina** [algolia/algoliasearch-client-ruby#239]
When trying to save a synonym with a numeric objectID, such as `save_synonym(12345, {...})`, it throws the following error: 

`TypeError: no implicit conversion of Fixnum into String`

It occurs in protocol.rb in this function:
```
def Protocol.synonym_uri(index, object_id)
  "#{synonyms_uri(index)}/#{CGI.escape(object_id)}"
end
```
Looks like it just needs to be updated to `CGI.escape(object_id.to_s)`, like how it's done in the `::to_query` method.

Not a huge deal since I can call `to_s` on the ID beforehand, just wanted to log this!

**Comment by julienbourdeau** [comment]
Thanks for filling this bug. I believe you're right, I open this PR to fix it: #327 
Any comments are welcome 👍
