### ISSUE TITLE
VCR and request uri

### ISSUE THREAD

**Issue by avbrychak** [algolia/algoliasearch-client-ruby#25]
Hello. I am trying to record requests and responses using [vcr](https://github.com/vcr/vcr) for my testing purposes.
When there is no request/response for a given test it would pass. But on the second run test will fail.

I've noticed the difference in URI when I am trying to get and object from algolia index:
On the firs run it would look like: 
`https://atc2cvtc1r-dsn.algolia.net/1/indexes/Gift_test_avbrychak/gift_2626`
On the second: 
`https://ATC2CVTC1R-1.algolianet.com/1/indexes/Gift_test_avbrychak/gift_2695`

I think the problem is in the changing part `-dsn`. Is it possible to use the same URI?

**Comment by redox** [comment]
HI @avbrychak,

that's actually a feature :) We're using different hostnames to cover fault-tolerance in an efficient & simple manner. The underlying list of hosts is defined here: https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/client.rb#L29-L30

What you could do it override the `hosts` and `search_hosts` option to a single host for testing purpose, so you would totally control it.

Does that make sense?

**Comment by avbrychak** [comment]
@redox that helped, thanks!

**Comment by dansteele** [comment]
@redox I'm having the same issue - is there a neat way to do this inside the rails version?
I understand that the Rails version uses a singleton class, rather than multiple client instances.

Might be worth adding to the docs since you suggest in multiple places to use VCR, and so I imagine this'd be relatively common 😄

**Comment by redox** [comment]
> @redox I'm having the same issue - is there a neat way to do this inside the rails version?
> I understand that the Rails version uses a singleton class, rather than multiple client instances.

@dansteele Just to be sure I understand; re-reading the issue from 2 years ago /o\ @dansteele the fallback on `<appid>-1.algolia.net` should only happen if the first call fails. Or is your VCR issue something else?

**Comment by dansteele** [comment]
As normally is the case, I've found out that I was just being dumb and this wasn't the issue!  🥇 

Thanks anyway 💯

**Comment by redox** [comment]
> As normally is the case, I've found out that I was just being dumb and this wasn't the issue! 🥇
> 
> Thanks anyway 💯

Ahah, good to hear 👍 You're welcome!
