### ISSUE TITLE
Scoped API Keys

### ISSUE THREAD

**Issue by taylorbrooks** [algolia/algoliasearch-client-ruby#26]
Wanting to generate public search keys scoped by `account_id`.

Doing this: 
```ruby
generated_public_key = Algolia.generate_secured_api_key("YourSearchOnlyApiKey, "numericFilters=account_id%3D{{account_id}})
```

And calling it in JS:
```javascript
var client = algoliasearch('my_application_id', '<%= generated_public_key %>');
```

And when I get a search the response in the web console is:
```
{name: "n", message: "Invalid Application-ID or API key"}
```

I don't get it.

**Comment by redox** [comment]
Arg yes indeed, you're using the old/deprecated way of this method requesting you to re-specify the filters in the JavaScript.

Before 1.4.2:

```ruby
generated_public_key = Algolia.generate_secured_api_key("YourSearchOnlyApiKey, "numericFilters=account_id%3D{{account_id}})
```

```js
var client = algoliasearch('my_application_id', '<%= generated_public_key %>');
client.setExtraHeader('X-Algolia-QueryParameters', 'numericFilters=user_id%3d42');
```

Today, you don't need to do that anymore because we're embedding those filters in the `generated_public_key`:

```ruby
generated_public_key = Algolia.generate_secured_api_key("YourSearchOnlyApiKey, { numericFilters: "account_id:#{account_id}" })
```

```js
var client = algoliasearch('my_application_id', '<%= generated_public_key %>');
```

Does that make sense?

**Comment by taylorbrooks** [comment]
Using  1.6.1, doing:
```ruby
Algolia.generate_secured_api_key("search_only_api_key", {numericFilters: "account_id=#{account_id}"})
```

Results in:
```ruby
ArgumentError: Attribute "tag_filters" must be a list of tags
```

**Comment by taylorbrooks** [comment]
If I wrap the 2nd argument in an array, 
```ruby
("search_only_api_key", [{numericFilters: "account_id=#{account_id}"}])
```
I get past the ```ArgumentError ```, but the generated key still returns a `403 Forbidden` when searching.

**Comment by taylorbrooks** [comment]
Fwiw, I was able to generate a valid key using the node client.

**Comment by redox** [comment]
> ArgumentError: Attribute "tag_filters" must be a list of tags

Hmmm, are you sure you're correctly using 1.6.1 because in this version this error can only be raised if the 2nd argument is not a hash. (https://github.com/algolia/algoliasearch-client-ruby/blob/cd53cd3fb4e34364dae19c2930d05c00636876dd/lib/algolia/client.rb#L487)

**Comment by taylorbrooks** [comment]
That may be on GitHub, but it's not what's published on Rubygems. Look at what you have tagged here:

https://github.com/algolia/algoliasearch-client-ruby/tree/1.6.1 or and it's head: a7e1392fded4d7fa1284df11c1d070230a2d03c0

I think you need to cut a new version.

**Comment by redox** [comment]
@taylorbrooks oh wow /o\ that explains everything... I've just released the `1.7.0` version, so sorry about that :/

**Comment by taylorbrooks** [comment]
Yep, that works now. Thanks.

**Comment by redox** [comment]
Thank you so much for your help investigating that @taylorbrooks, much appreciated :100: :+1:
