### ISSUE TITLE
copy_index! waits forever when copying a non-existent index

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-ruby#267]
Calling `copy_index!('foo', 'bar')` when `foo` does not exists will result in the method hanging forever.

### What happened?

- The API will accept the job, even if `foo` does not exist (this is because the index *might* exist in the future, when the job will be processed).
- The API will return a `taskID`, bound to the `foo` index.
- When the job will be executed, the job will do nothing, because `foo` does not exist. The API will move to the next job.
*Note: It is not entirely true that the job will do nothing. It will still create `bar` actually*

From a user standpoint, it means that we receive a `taskID`, bound to an index that does not exist. Listening for this `taskID` will result in an 400 error (`index foo does not exist`), and `copy_index!` will just wait forever for this to resolve.

### Solution 1: Raising the error from the wait_task to the copy_index!

It seems that `copy_index!` is swallowing the error returned by the API. Maybe it should abort its processing if the check to the `taskID` returns an error. This might be tricky because as said above, it might be perfectly fine for this call to return an error if the index does not exist yet, but will exist when the job will be processed.

### Solution 2: Forcing the API to reject the job if the source index does not exist

This is breaking the asynchronous paradigm of our API, but could be acceptable in that case maybe? What are the use-cases where you would try to copy a non-existent index, knowing that it will exists when the job will be executed?

### Solution 3: Checking for the existence of the index before doing the copy

This is what I do in jekyll-algolia: I first do a `get_settings` to the index to check if it exists before sending a `copy_index!` job. If the index is not here, I just don't do it. This might be a check we could add to the Ruby API Client as well (but that would mean adding it to all API Clients as well).

cc @ercolanelli-leo @Nagriar @clement-leprovost @adrienjoly

**Comment by redox** [comment]
> Calling copy_index!('foo', 'bar') when foo does not exists will result in the method hanging forever.

I don't think this is related to the Ruby API client, but OK to have the discussion here.

> This is what I do in jekyll-algolia: I first do a get_settings to the index to check if it exists before sending a copy_index! job. If the index is not here, I just don't do it. This might be a check we could add to the Ruby API Client as well (but that would mean adding it to all API Clients as well).

I would rather do a `set_settings({})` (with empty settings) to create the source index if it doesn't exist. Safer (in case the build of the index was in progress).

**Comment by redox** [comment]
> Solution 2: Forcing the API to reject the job if the source index does not exist
> This is breaking the asynchronous paradigm of our API, but could be acceptable in that case maybe? What are the use-cases where you would try to copy a non-existent index, knowing that it will exists when the job will be executed?

This is not possible, you don't know what is enqueued.

**Comment by pixelastic** [comment]
Posting it here because that's where I encountered the issue. Still unsure if this is a Ruby or API question. We can move the discussion elsewhere if more appropriate.

> I would rather do a set_settings({}) (with empty settings) to create the source index if it doesn't exist 
Make sense. That would be more in line with what the expected outcome would be?

**Comment by raphi** [comment]
https://github.com/algolia/AlgoliaSaaS/issues/845

**Comment by julienbourdeau** [comment]
Do you think this could be fixed only via documentation. We could explain how to works and propose 2 solutions the user can implements:

1. `setSettings` before `copyIndex`
2. `getSettings` before to check of the index exists
3. Don't wait on `copy_index` operations 😄 (wait on the operations you're doing on this new index)

I guess there are only very few usecase where you need to wait for a copy index but I might be missing something.

**Comment by pixelastic** [comment]
We should document this edge-case for sure, so people quickly find a workaround. Returning a `taskID` that cannot be used is not very friendly. 

My POV is that when calling `copy_index!` (note the __!__) my intent is to make sure the index is correctly copied before moving to the next line of my script. In that case, I think it's fair to call a blocking `get_settings` before. It might be slower, but we're sure we'll get the end result the user expected.

As for the use-cases, it's useful when you might have HTTP race conditions. For example, I need to copy index `foo` to `bar`, then send a bunch of batch operations to `bar`. If, for whatever reason, my HTTP call for `copy_index` arrives __after__ my batch, then all my batches operations might get deleted by the `copy`.

**Comment by julienbourdeau** [comment]
In the end, we won't handle in the client. Each implementation should decide what strategy they want to use.

I open a request on our docs, I believe this limitation will be added to the `copy_index` page.

**Comment by pixelastic** [comment]
I agree. I think having the documentation warning about what happens when copying a non-existent index should be enough. Documentation should also include the `set_settings({})` trick to create an empty index. Or maybe the API clients have a `create_empty_index` method wrapping that call?
