### ISSUE TITLE
Client review

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-client-ruby#269]
List of things to change (if possible)

- [x] `index.search` rename params to searchParameters
- [x] `search_for_facet_value` rename parameters
- [x] Fix browse (and doc snippets)
- [x] `delete_objects` pass objectIds list
- [x] `wait_task` timeBeforeRetry arg ?
- [x] `get_settings` remove options?
- [x]  `Algolia.init` refactor ENV['xxx'] ?

**Comment by raphi** [comment]
@julienbourdeau what are the valid Algolia ENV vars? `ALGOLIA_API_ID`, `ALGOLIA_APPLICATION_ID`, any others?

**Comment by julienbourdeau** [comment]
* `ALGOLIA_APP_ID` or `ALGOLIA_APPLICATION_ID` for the app id (use short version if possible)
* `ALGOLIA_API_KEY` for the almost-admin key
* `ALGOLIA_SEARCH_API_KEY` for the search only key

Do you need places or MCM credentials as well?

**Comment by raphi** [comment]
Alright thanks I will add `ALGOLIA_APP_ID` in the ruby client then. No I don't need the places one for this client; MCM maybe when we will add it :trollface:
