### ISSUE TITLE
Requests on different timeouts have no guaranteed order

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-client-ruby#27]
This is mostly an issue for `batch` vs `send`.
Both types of requests use a different connection pool, which means they can end up on different machines (no keep-alive guarantee here).

So if we send a `batch` immediately followed by a `move_index` or a `delete_index`, if they share the same timestamp, the consensus might reorder them.

I don't know how we should fix it. It might be by documenting the fact the `move` or `delete` should wait on the previous indexing task.

It might also simply be by adding a `sleep 1` to ensure the timestamps are different.

**Comment by redox** [comment]
This is now fixed with the latest `httpclient`. See https://github.com/nahi/httpclient/pull/295 & https://github.com/nahi/httpclient/pull/315
