### ISSUE TITLE
Algolia.delete_index raises an error

### ISSUE THREAD

**Issue by hdorio** [algolia/algoliasearch-client-ruby#277]
> gem version  1.19.1

`Algolia.delete_index` and `Algolia.delete_index!` raise an ArgumentError
`ArgumentError: wrong number of arguments (given 2, expected 1)`

https://github.com/algolia/algoliasearch-client-ruby/blob/223a45e0c717502184ce78259f8a04549f0dbe2c/lib/algolia/client.rb#L637
https://github.com/algolia/algoliasearch-client-ruby/blob/223a45e0c717502184ce78259f8a04549f0dbe2c/lib/algolia/client.rb#L198
https://github.com/algolia/algoliasearch-client-ruby/blob/223a45e0c717502184ce78259f8a04549f0dbe2c/lib/algolia/client.rb#L643
https://github.com/algolia/algoliasearch-client-ruby/blob/223a45e0c717502184ce78259f8a04549f0dbe2c/lib/algolia/client.rb#L204

**Comment by raphi** [comment]
Indeed seems like a bug ! Thanks for reporting, will fix that asap

**Comment by raphi** [comment]
@hdorio thanks for reporting this! Gem `1.19.2` is published
