### ISSUE TITLE
AlgoliaProtocolError is not reliably switchable

### ISSUE THREAD

**Issue by dpatti** [algolia/algoliasearch-client-ruby#28]
Sometimes our users search for unreasonably large strings and we get back an `AlgoliaProtocolError` object with a `message` attribute that looks like this:

``` ruby
"Cannot POST to https://<snip>.algolia.io/1/indexes/*/queries: {\"message\":\"query string too long\",\"status\":400}\n (400)"
```

There's also a `status` attribute that is just `400`. I want to be able to handle this specific error since in our case it is a user error, but I don't want to catch all algolia errors or all algolia errors with a status code of 400.  The best I can do right now is

``` ruby
e.message =~ /query string too long/
```

But I would rather have a more reliable way to access the API response, which I would expect to be more stable (and hopefully one day documented).

**Comment by raphi** [comment]
Hey @dpatti sorry for the delay...

This is definitely a good point, we can do much better here. We are starting discussing it and see what's the best approach for all clients to handle that.

**Comment by fpalluel** [comment]
Hello,
Did your discussion lead to a consensus on error handling ?
It would be great if we could have an 'AlgoliaApiError', with easily manageable information.

Right now we have to parse the message string to extract those information, which is far from reliable ;-)
We may propose a PR.

Thanks !

**Comment by julienbourdeau** [comment]
We could add different errors, which should extends the currrent `AlgoliaProtocolError` but they can only be defined by the status code. In this case, you would get a `AlgoliaBadRequestError` with the error message from the API.

You can use this message to act on it, but bare in mind that they are not part of the backward compatibility promise. They can change at any time, without prior notice.

**Comment by raphi** [comment]
@julienbourdeau why can't we define errors based on the message as well?

**Comment by fpalluel** [comment]
One suggestion : apply [this RFC](https://tools.ietf.org/html/rfc7807).
Among several other features, it clearly separates the concerns : 
- inform the user with human readable sentences, via ```title``` and/or ```details```
- provide easily parsable information, which can be used to properly handle the error (retries, for instance), via the ```extensions```

**Comment by raphi** [comment]
@julienbourdeau this might a broader topic than just API clients but since we are focusing on DX10, this seems like fundamental to me... And the core engine is supposed to be retrocompatible. 

Even if it's not, we could match current error messages and do a fallback if we don't it (new one or updated one).

**Comment by chloelbn** [comment]
The aim for the v2 is to have AlgoliaError and AlgoliaApiError retrieving the message and code from the engine. I'm closing this issue, don't hesitate and reopen it if you think something is still missing.
