### ISSUE TITLE
index.delete_object() seems to require more authorization than it should

### ISSUE THREAD

**Issue by thibauld** [algolia/algoliasearch-client-ruby#29]
I am trying to delete an object from my Algolia index in ruby.
```
Bot::Candidates.index.delete_object(candidate_id)
```

I get the following error:
```
Cannot DELETE to https://MYID.algolia.net/1/indexes/candidates/: {"message":"Method not allowed with this API key","status":403}
```

My API key has the following ACL:
```
search,addObject,deleteObject
```

When I try the same operation from the REST API, it works without a glitch:
```
curl -X DELETE -H "X-Algolia-API-Key: <sameapikeyasabove>" -H "X-Algolia-Application-Id: MYID" "https://MYID.algolia.net/1/indexes/candidates/<objectID>"
```
after checking the task status, I get:
```
{"status":"published","pendingTask":false}
```

What is it working with the REST api and not with the ruby wrapper ? Is the ruby wrapper performing another operation than simply delete ?

**Comment by redox** [comment]
> I am trying to delete an object from my Algolia index in ruby.
> 
> Bot::Candidates.index.delete_object(candidate_id)
> I get the following error:
> 
> Cannot DELETE to https://MYID.algolia.net/1/indexes/candidates/: {"message":"Method not allowed with this API key","status":403}

I think your `candidate_id` is nil, making the `https://MYID.algolia.net/1/indexes/candidates/<OBJECT_ID>` URI to be `https://MYID.algolia.net/1/indexes/candidates/` which is actually the URL to delete the whole index /o\

I'll add a check to ensure no one does that :)

**Comment by redox** [comment]
Done in https://github.com/algolia/algoliasearch-client-ruby/commit/3d2872ea4237bdbad445547960cd9aacc6fdaeb7

**Comment by thibauld** [comment]
Indeed, you are right. Sorry for the misleading bug report ! I was mislead myself by the error message :)

**Comment by redox** [comment]
> Indeed, you are right. Sorry for the misleading bug report ! I was mislead myself by the error message :)

That's fine :) :+1:
