### ISSUE TITLE
Cannot load such file -- algolia/analytics

### ISSUE THREAD

**Issue by GuillaumeWrobel** [algolia/algoliasearch-client-ruby#305]
```
LoadError: cannot load such file -- algolia/analytics
```

- Algolia Client Version: 1.23.0
- Language Version: ruby 2.5.1

**Comment by julienbourdeau** [comment]
Hi @GuillaumeWrobel, can you share how you got this error?

**Comment by julienbourdeau** [comment]
It's fixed, I forgot to update the .gemspec. Sorry for that and thanks again for reporting the issue 👍

**Comment by GuillaumeWrobel** [comment]
You're welcome @julienbourdeau !
