### ISSUE TITLE
Custom user agent is displayed in wrong position 

### ISSUE THREAD

**Issue by amcdaid106** [algolia/algoliasearch-client-ruby#310]
- Algolia Client Version: 1.23.0
- Language Version: all

### Description
Fix for issue on Dashboard where the wrong User agent was being displayed (Rails should be listed first instead of Ruby)

`algolia_for_ruby_(1.23.2);_ruby_(2.3.1);_algolia_for_rails_(1.20.4);_algolia_for_ruby_(1.23.2)`

**Comment by julienbourdeau** [comment]
For future reference, see my response here: https://github.com/algolia/algoliasearch-client-ruby/pull/311#issuecomment-447900700
