### ISSUE TITLE
Multiple algolia apps

### ISSUE THREAD

**Issue by USvER** [algolia/algoliasearch-client-ruby#313]
```
Algolia.init(application_id: 'YourApplicationID', api_key:        'YourAPIKey')
```
This implies that only one application can be managed at the same time.
What should i do if i need to manage multiple apps?

**Comment by raphi** [comment]
Hi @USvER 

You can simply store the returned client in a variable, and call this method multiple times:

```
client_one = Algolia.init(application_id: 'APP_ID_1', api_key: 'API_KEY')
client_two = Algolia.init(application_id: 'APP_ID_2', api_key: 'API_KEY')
```

Enjoy

**Comment by USvER** [comment]
Thanks! I was under impression that `.init` stores `application_id` and `api_key` in global variables and will interfere each other.

**Comment by raphi** [comment]
Indeed, for backward compatibility, we kept it. Each time you call `.init`, it keeps the last client as a singleton. If you use `Algolia.methods`, it will use the most recent instantiated client. But we don't recommend to use these methods. Instead, we've implemented them inside each Client and Index class as well, and we encourage you to use these!

**Comment by USvER** [comment]
Thank you for explanation! Now everything clear!

**Comment by Spone** [comment]
> Hi @USvER
> 
> You can simply store the returned client in a variable, and call this method multiple times:
> 
> ```
> client_one = Algolia.init(application_id: 'APP_ID_1', api_key: 'API_KEY')
> client_two = Algolia.init(application_id: 'APP_ID_2', api_key: 'API_KEY')
> ```
> 
> Enjoy

:warning: **Warning!** If you do that in a Rails app (that uses `algoliasearch-rails`) you will need to call the `Algolia.init` method once again with your standard parameters, else you will end up with the latest Algolia application as the default.

Here is what we ended up doing:

```
client_one = Algolia.init(application_id: 'APP_ID_1', api_key: 'API_KEY')
client_two = Algolia.init(application_id: 'APP_ID_2', api_key: 'API_KEY')

Algolia.init(
  application_id: AlgoliaSearch.configuration[:application_id],
  api_key: AlgoliaSearch.configuration[:api_key]
)
```

But it's clearly not ideal. I hope the `algoliasearch-rails` gem will support multiple Algolia apps in the future.
