### ISSUE TITLE
The helpers.highlight mustache syntax is broken in API Clients READMEs

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-ruby#343]
**Describe the bug**

It generates:

```
      <p class="hit-name">
        {}{ "attribute": "firstname" }{{/helpers.highlight}}
        {}{ "attribute": "lastname" }{{/helpers.highlight}}
      </p>
```

instead of

```
      <p class="hit-name">
        {{#helpers.highlight}}{ "attribute": "firstname" }{{/helpers.highlight}}
        {{#helpers.highlight}}{ "attribute": "lastname" }{{/helpers.highlight}}
      </p>
```

**To reproduce**

Ex: https://github.com/algolia/algoliasearch-client-ruby/blob/master/README.md

<img width="656" alt="Screenshot 2019-05-21 at 08 50 10" src="https://user-images.githubusercontent.com/29529/58074502-afc11e00-7ba5-11e9-9eba-9546524123cb.png">

**Comment by nunomaduro** [comment]
We no longer have that example on the readme.
