### ISSUE TITLE
Feature Request: "Overall" timeout or clearer explanation of expected overall timeout

### ISSUE THREAD

**Issue by peeinears** [algolia/algoliasearch-client-ruby#373]
- Algolia Client Version: 1.27.1
- Language Version: 2.5.1

### Description
The client cycles through multiple hosts if requests fail. (Additionally there's [this code](https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/client.rb#L581-L583) which I don't quite understand.) Because of this, the overall experienced timeout can be much longer than any individual configured timeout. As a user of this client, it can be hard to know what maximum timeout to expect.

During a recent Algolia outage, we noticed failed search requests were taking 12 seconds before timing out, tying up instances of our web server for longer than we'd like. As a response, we want to change the search timeout to something shorter than the default, which I expected to be 12 seconds but is actually 5. It's not obvious where 12 seconds came from and it's difficult to know what overall maximum timeout to expect if I change the `search_timeout` to, say, 2 seconds.

One proposal is for some "overall" timeout configuration that raises an exception after the timeout was reached regardless of where you are in the request or retry cycle. Or, if there was clearer documentation on expected overall timeout, perhaps these setting isn't needed.

**Comment by swistak35** [comment]
We'd be also very interested in possibility to set hard timeout for an operation, so we can ensure that if algolia is unstable for a moment, it doesn't cause cascading failure on our side.

**Comment by chloelbn** [comment]
This feature is implemented in v2 that will be out in a few weeks
