### ISSUE TITLE
If available, ensure that Analytics' regions are "us" and "de" (not "eu")

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-ruby#382]
We've recently discovered that at least one API client was exposing "eu" as a
valid region for the Analytics client implementation, which is wrong. Only the
following regions are available at the moment to the Analytics client:

 - "us"
 - "de"

**Comment by chloelbn** [comment]
The region option is not available in the Ruby client
https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/analytics.rb#L5
