### ISSUE TITLE
delete_by_query(nil) wipes entire index

### ISSUE THREAD

**Issue by dustincoates** [algolia/algoliasearch-client-ruby#40]
`index.delete_by_query(nil)`

End result is 0 records in the relevant index.

**Comment by rayrutjes** [comment]
Its not a bug... its a feature... Actually it calls the standard search endpoint and then deletes the resulting ids. Funny thing, we discussed this with @maxiloc and we found that this method is weird, and that it would be more useful if it were based on an underlying "browse " call. Who wants to delete records based on their positive ranking? Am I missing a use case where it would make sense?

**Comment by redox** [comment]
I assume we're then doing an empty query (so match all). We can definitely raise an `ArgumentError` because we should anyway use `clear` to wipe the entier index.

**Comment by rayrutjes** [comment]
@redox can you think of any valid use case for this method? I find it a bit scary. Like "delete the results you think you should delete".

**Comment by redox** [comment]
> it would be more useful if it were based on an underlying "browse " call.

Oh yeah it should; but when it has been implemented we didn't have the `browse` yet, definitely need to move to browse.

> can you think of any valid use case for this method

Yes, it when you want to delete all records belonging to a user (`delete_by_query('', tagFilters: 'user_42')`) for instance.

**Comment by figgybit** [comment]
I have also experienced this same issue via these calls.

public_index = Algolia::Index.new("Public_Variant")
public_index.delete_object(nil)

End result is 0 records in the relevant index.
