### ISSUE TITLE
`#multiple_queries` raises NoMethodError if params are omitted

### ISSUE THREAD

**Issue by joelcogen** [algolia/algoliasearch-client-ruby#479]
- Algolia Client Version: 2.2.3, 2.2.4
- Language Version: Ruby 3.0.2

### Description
Calling `#multiple_queries` without `params` (documented as optional) raises a NoMethodError due to a subsequent call to `to_query_string`

### Steps To Reproduce
Call `#multiple_queries` with only required parameters `indexName` and `query`:
```
client.multiple_queries([{ indexName: index_name, query: "something" }])
```

**Comment by DevinCodes** [comment]
Releasing this in v2.2.5! 🚀  Thank you again
