### ISSUE TITLE
Timeouts not being passed to http_requester

### ISSUE THREAD

**Issue by jmccormick11** [algolia/algoliasearch-client-ruby#494]
- Algolia Client Version: 2.3.1
- Language Version: All

### Description
Timeout's are not being sent to the http_requester for sending a request

The intention is to end up with the `timeout` and `connect_timeout` keys present in the request object that is later passed to `send_request`

https://github.com/algolia/algoliasearch-client-ruby/blob/c8c8c6b79d34e4788daeb04e1003695c010c87d6/lib/algolia/transport/transport.rb#L51-L69

But in fact those keys are not being added in the `build_request` method

https://github.com/algolia/algoliasearch-client-ruby/blob/c8c8c6b79d34e4788daeb04e1003695c010c87d6/lib/algolia/transport/transport.rb#L93-L100

I created a work in progress PR that shows the fix:  https://github.com/algolia/algoliasearch-client-ruby/pull/493

**Comment by DevinCodes** [comment]
PR has been merged and changes have been released in [version 2.3.2](https://rubygems.org/gems/algolia/versions/2.3.2)! Thank you again for your contribution 😄
