### ISSUE TITLE
Cannot reach any host: execution expired

### ISSUE THREAD

**Issue by sullerandras** [algolia/algoliasearch-client-ruby#82]
We keep getting this error in our application:
```
ERROR -- : 0: Cannot reach any host: execution expired, execution expired, execution expired, execution expired
/usr/local/bundle/gems/algoliasearch-1.10.0/lib/algolia/client.rb:351:in `request'
/usr/local/bundle/gems/algoliasearch-1.10.0/lib/algolia/client.rb:359:in `post'
/usr/local/bundle/gems/algoliasearch-1.10.0/lib/algolia/index.rb:548:in `batch'
/usr/local/bundle/gems/algoliasearch-1.10.0/lib/algolia/index.rb:271:in `save_objects'
```

When this happens, the application will stay in this state forever (e.g. getting this exact error in every 80 seconds). Sometimes this error occurs just a few minutes after the application started, sometimes it takes weeks to occur. Couldn't find any pattern.
Calling `Algolia.destroy` then `Algolia.init` does *not* solve the problem. The only solution we have so far is to restart the application.
Why is this happening and what can we do to avoid this error?
Using Ruby 2.3.1, Ubuntu 14.04, kernel 4.4.0. Thanks.

**Comment by redox** [comment]
Hi @sullerandras,

that's so weird :/ Never saw that before...

Do you mind upgrading to the latest `1.11` so it uses the latest underlying `httpclient` and see if it's better?

**Comment by aseure** [comment]
An other customer (a Rails integration user actually) also mentioned a similar issue on support. Our diagnostic tool didn't find anything. The only temporary solution has been to increase the timeouts of the Rails configuration.

The error is the same:
> Cannot reach any host: execution expired, execution expired, execution expired, execution expired

+1 on this issue.

**Comment by redox** [comment]
@sullerandras did you try to upgrade to `1.11.0` ?

**Comment by sullerandras** [comment]
I managed to upgrade to 1.11 a few days ago. So far there are no errors.

**Comment by redox** [comment]
> I managed to upgrade to 1.11 a few days ago. So far there are no errors.

Alright. Closing the issue for now; but feel free to re-open if you experience the error one more time!
